### ISSUE TITLE
Bind is not instantiable

### ISSUE THREAD

**Issue by twdnhfr** [michael-rubel/laravel-enhanced-container#1]
Hey, 

I am using PHP 8.0.11 and Laravel v8.62.0.

After installing this package I changed my AppServiceProvider from:

```
$this->app->bind(
    ServerOrderInterface::class,
    FakeServerOrderService::class
);
```

to:

```
bind(ServerOrderInterface::class)->to(FakeServerOrderService::class);
```

And basically everything broke with:

```
Illuminate\Contracts\Container\BindingResolutionException 

Target [MichaelRubel\EnhancedContainer\Bind] is not instantiable.
```

**Comment by michael-rubel** [comment]
Hello, twdnhfr!

Looks like the `CallServiceProvider` wasn't registered by auto-discovery for some reason in your case.
Have you tried to run `php artisan package:discover` and maybe `composer dump-autoload`?

Let me know if it helps.

**Comment by michael-rubel** [comment]
Anyway, in version `1.6.2+` bind is now not dependent on the Service Provider. It should resolve this issue.

Feel free to reopen the issue if you think it isn't fixed.
