### ISSUE TITLE
implicit nullable parameter deprecation warning with php 8.4 

### ISSUE THREAD

**Issue by ainesophaur** [michael-rubel/laravel-enhanced-container#31]
Two deprecation warnings are generated using php 8.4.

> Deprecated: Illuminate\Container\Container::makeOr(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in michael-rubel/laravel-enhanced-container/src/Overrides/Container.php on line 770

> Deprecated: Illuminate\Container\Container::remember(): Implicitly marking parameter $callback as nullable is deprecated, the explicit nullable type must be used instead in michael-rubel/laravel-enhanced-container/src/Overrides/Container.php on line 793

 Since the package requires at least php 8.3 it should be just adding the nullable option to the parameter types

```php
public function makeOr($abstract, $parameters = [], ?Closure $callback = null) {
...
}
```

**Comment by michael-rubel** [comment]
Thanks for the report @ainesophaur!

Are you willing to contribute? 😊

If not, I'll look into it on the weekend.

**Comment by ainesophaur** [comment]
Certainly, however, dependency updates are required to test on php 8.4 (`brianium/paratest`, `phpunit/phpunit` just to name a few). Let me know if you'd want the contribution to include those updates or just fix the issue w/o testing (since the nullable parameter change is very minor)

**Comment by michael-rubel** [comment]
I've updated the PR a bit, and tagged the [13.0.3](https://github.com/michael-rubel/laravel-enhanced-container/releases/tag/13.0.3)

Thanks!
